# flyway-sqlite.conf

# Đường dẫn đến file SQLite của bạn
flyway.url=jdbc:sqlite:./data/hrm.db
# flyway.url=jdbc:sqlite:C:\Users\admin\Desktop\work\bv\hrm.db

# Thư mục chứa các file SQL dành riêng cho SQLite
flyway.locations=filesystem:./sqlite_migrations

# Tự động Baseline nếu là DB cũ đã có data
flyway.baselineOnMigrate=true
flyway.baselineVersion=1

# Tên bảng lịch sử (Có thể giữ mặc định hoặc đổi để phân biệt)
flyway.table=flyway_schema_history