# flyway.conf

# URL kết nối đến MySQL (Đảm bảo đã tạo database bnd_face_recog trước)
flyway.url=jdbc:mysql://192.168.12.209:3306/hrm_db?allowPublicKeyRetrieval=true&useSSL=false

# User và Password của MySQL
flyway.user=admin
flyway.password=Donghung@1234#

# Thư mục chứa các file SQL (V1, V2...)
flyway.locations=filesystem:./sql_migrations

# Tùy chọn: Cho phép Flyway tự tạo bảng quản lý nếu chưa có
flyway.baselineOnMigrate=true